config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  get 'sessions/logout'
  get 'sessions/omniauth'
  get 'users/show'
  get 'welcome/index'

  resources :items, only: %i[index show edit update create new destroy] do
    member do
      patch :set_status
    end
  end
  resources :user_profiles
  resources :users do
    member do
      patch :update_auth_level
    end
  end
  resources :items do
    collection do
      post :import
    end
  end

  root 'welcome#index'
  get 'welcome/index', to: 'welcome#index', as: 'welcome'

  get '/logout', to: 'sessions#logout', as: 'logout'
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
  get '/add_note_to_item', to: 'items#add_note', as: 'add_note'

  post '/create_new_event', to: 'events#new', as: 'create_event'
  get '/publish_event', to: 'events#publish_event', as: 'publish_event'

  get 'export_items', to: 'items#export', as: 'export_items'

  get 'admin/login', to: 'admin_sessions#new', as: 'admin_login'
  post 'admin/login', to: 'admin_sessions#create'
  delete 'admin/logout', to: 'admin_sessions#destroy', as: 'admin_logout'
  get 'admin/dashboard', to: 'admin_sessions#dashboard', as: 'admin_dashboard'
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

# Tests logins upon first launch.
class WelcomeController < ApplicationController
  skip_before_action :require_login, only: [:index]
  def index
    return unless logged_in?

    redirect_to user_path(@current_user), notice: 'Welcome, back!'
  end
end

app/views/welcome/index.html.erb
<%= stylesheet_link_tag 'users', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="welcome">
<div id="welcome-section">
    <h1>Welcome to Stock'Em</h1>
    <p>Your One Stop Solution to All Your Capstone Needs</p>
    <div style="display: flex; flex-direction: row; justify-content: space-around">
    <%= button_to "Login with Google", "/auth/google_oauth2", data: { turbo: "false" }, class: "btn-start", style: "margin-left: 0" %>
    <%= button_to "Login as Admin", admin_login_path, class: "btn-start", style: "margin-left: 0" %>
    </div>
</div>
</div>