config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  get 'sessions/logout'
  get 'sessions/omniauth'
  get 'users/show'
  get 'welcome/index'

  resources :items, only: %i[index show edit update create new destroy] do
    member do
      patch :set_status
    end
  end
  resources :user_profiles
  resources :users do
    member do
      patch :update_auth_level
    end
  end
  resources :items do
    collection do
      post :import
    end
  end

  root 'welcome#index'
  get 'welcome/index', to: 'welcome#index', as: 'welcome'

  get '/logout', to: 'sessions#logout', as: 'logout'
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
  get '/add_note_to_item', to: 'items#add_note', as: 'add_note'

  post '/create_new_event', to: 'events#new', as: 'create_event'
  get '/publish_event', to: 'events#publish_event', as: 'publish_event'

  get 'export_items', to: 'items#export', as: 'export_items'

  get 'admin/login', to: 'admin_sessions#new', as: 'admin_login'
  post 'admin/login', to: 'admin_sessions#create'
  delete 'admin/logout', to: 'admin_sessions#destroy', as: 'admin_logout'
  get 'admin/dashboard', to: 'admin_sessions#dashboard', as: 'admin_dashboard'
end

app/models/item.rb
# frozen_string_literal: true

# Contains everything Item-related
class Item < ApplicationRecord
  has_many :notes, dependent: :destroy

  has_many :events, dependent: :destroy

  VALID_CATEGORIES = ['Mobile Devices',
                      'Development Boards and Kits',
                      'Sensors and Modules',
                      'Computer Accessories',
                      'Displays',
                      'Cables and Connectors',
                      'Miscellaneous Components and Kits', 'Furnitures', 'Electronics'].freeze
  validates :item_name, presence: true, length: { minimum: 3, maximum: 50 }
  validates :quality_score,
            numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }
  validates :serial_number, presence: true, uniqueness: true
  validates :category, inclusion: { in: VALID_CATEGORIES }
  validates :currently_available, inclusion: { in: [true, false] }

  require 'csv'
  def self.to_csv
    posts = all
    CSV.generate do |csv|
      csv << column_names
      posts.each do |post|
        csv << post.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

# Contains logic for web pages which display item(s)
class ItemsController < ApplicationController # rubocop:disable Metrics/ClassLength
  include EventLogger
  # get all the items
  def index # rubocop:disable Metrics/AbcSize
    @items = Item.all

    apply_keyword_search if params[:query].present?
    apply_category_filter if params[:category].present?
    apply_status_filter if params[:status].present?
    apply_availability_filter if params[:available_only] == '1'

    @categories = Item.distinct.pluck(:category)
    @statuses = Item.distinct.pluck(:status)
  end

  def apply_keyword_search
    keywords = params[:query].split(' ')
    query_conditions = generate_query_conditions(keywords)
    query_params = generate_query_params(keywords)

    @items = @items.where(query_conditions, *query_params)
  end

  def generate_query_conditions(keywords)
    condition = <<-SQL.strip_heredoc
      (LOWER(item_name) LIKE :keyword OR#{' '}
      LOWER(category) LIKE :keyword OR#{' '}
      LOWER(status) LIKE :keyword OR#{' '}
      LOWER(CASE WHEN currently_available THEN 'available'#{' '}
      ELSE 'not available' END) LIKE :keyword)
    SQL

    keywords.map { condition }.join(' AND ')
  end

  def generate_query_params(keywords)
    keywords.flat_map { |keyword| { keyword: "%#{keyword.downcase}%" } }
  end

  def apply_category_filter
    @items = @items.where(category: params[:category])
  end

  def apply_status_filter
    @items = if params[:status] == 'unknown'
               @items.where(status: nil)
             else
               @items.where(status: params[:status])
             end
  end

  def apply_availability_filter
    @items = @items.select(&:currently_available)
  end

  # def index
  #   @items = Item.all

  #   # if params[:query].present?
  #   #   query = params[:query].downcase
  #   #   @items = @items.select do |item|
  #   #     item.item_name.downcase.include?(query) || item.category.downcase.include?(query)
  #   #   end
  #   # end

  #   @categories = Item.distinct.pluck(:category)
  #   @statuses = Item.distinct.pluck(:status)

  #   if params[:query].present?
  #     keywords = params[:query].split(' ')

  #     condition = <<-SQL.strip_heredoc
  #       (LOWER(item_name) LIKE :keyword OR#{' '}
  #       LOWER(category) LIKE :keyword OR#{' '}
  #       LOWER(status) LIKE :keyword OR#{' '}
  #       LOWER(CASE WHEN currently_available THEN 'available'#{' '}
  #       ELSE 'not available' END) LIKE :keyword)
  #     SQL

  #     # Map keywords to SQL conditions and join them with 'AND'
  #     query_conditions = keywords.map { condition }.join(' AND ')

  #     # Map each keyword into a hash format to be used in the query
  #     query_params = keywords.flat_map { |keyword| { keyword: "%#{keyword.downcase}%" } }

  #     # Apply the query
  #     @items = @items.where(query_conditions, *query_params)

  #   end

  #   @items = @items.where(category: params[:category]) if params[:category].present?

  #   if params[:status].present?
  #     @items = if params[:status] == 'unknown'
  #                @items.where(status: nil)
  #              else
  #                @items.where(status: params[:status])
  #              end
  #   end

  #   return unless params[:available_only] == '1'

  #   @items = @items.select(&:currently_available)
  # end

  # get specific item
  def show
    @item = Item.find(params[:id])
    @writing_note = !params[:writing_note].nil?
    @notes = Note.where(item_id: @item.id).order('created_at DESC')
    @events = Event.where(item_id: @item.id).order('created_at DESC')
  end

  # create new item
  def new
    @item = Item.new
    render :new
  end

  def create # rubocop:disable Metrics/AbcSize,Metrics/MethodLength
    Rails.logger.info("Current user auth level: #{current_user.auth_level}")
    @item = Item.new(item_params)
    if current_user.auth_level != 0
      if Item.exists?(serial_number: @item.serial_number)
        flash[:alert] = 'Item already exists with this serial number.'
        render :new
      elsif @item.save
        redirect_to items_path, notice: 'Item was successfully created.'
      else
        render :new
      end
    else
      flash[:alert] = 'You are not authorized to perform this action.'
      redirect_to items_path
    end
  end

  # add note to item
  def add_note # rubocop:disable Metrics/AbcSize,Metrics/MethodLength
    @item = Item.find(params[:id])

    if current_user.auth_level == 1 || current_user.auth_level == 2 # Assuming auth_level 2 is for admins
      Note.create!({
                     note_id: '',
                     item: @item,
                     msg: params[:note_msg],
                     user: User.find_by(id: session[:user_id]),
                     created_at: DateTime.now,
                     updated_at: DateTime.now
                   })

      flash[:notice] = 'Note successfully added.'
    else
      flash[:alert] = 'You need to be an admin or assistant to update the status of this item.'
    end

    respond_to do |format|
      format.html { redirect_to item_path(@item) }
      format.json { head :no_content }
    end
  end

  def update # rubocop:disable Metrics/AbcSize,Metrics/MethodLength,Metrics/PerceivedComplexity
    @item = Item.find(params[:id])
    Rails.logger.info("Current user auth level: #{current_user.auth_level}")
    if current_user.auth_level == 2
      original_params = item_params.dup
      if @item.update(item_params)
        if params[:item][:status] == 'Not Available' || params[:item][:status] == 'Lost'
          @item.update(currently_available: false) # Update available to false
        end
        if params[:item][:status] == 'Damaged' || params[:item][:status] == 'Available'
          @item.update(currently_available: true) # Update available to false
        end
        log_event(params[:id], 'item_edit', 'Item attributes have been updated.', session[:user_id])
        flash[:notice] = 'Item was successfully updated.'
      else
        flash[:alert] = 'There was a problem updating the item.'
        @item.update(original_params)
      end
      redirect_to @item
    else
      flash[:alert] = 'You are not authorized to perform this action.'
      redirect_to item_path(@item)
    end
  end

  def destroy # rubocop:disable Metrics/AbcSize,Metrics/MethodLength
    @item = Item.find(params[:id])
    Rails.logger.info("Current user auth level: #{current_user.auth_level}")
    if current_user.auth_level == 2
      if @item.destroy
        flash[:notice] = 'Item was successfully deleted.'
        redirect_to items_path
      else
        flash[:alert] = 'Failed to delete the item.'
        redirect_to item_path(@item)
      end
    else
      flash[:alert] = 'You need to be an admin to delete items.'
      redirect_to item_path(@item)
    end
  end

  def set_status # rubocop:disable Metrics/AbcSize,Metrics/MethodLength
    @item = Item.find(params[:id])
    @notes = Note.where(item_id: @item.id).order('created_at DESC')

    if current_user.auth_level.zero?
      flash[:alert] = 'You need to be an admin or assistant to update the status of this item.'
      redirect_to item_path(@item) and return
    end

    valid_statuses = [nil, 'Damaged', 'Lost', 'Not Available', 'Intact']
    status = get_valid_status(item_params[:status])

    if valid_statuses.include?(status) && @item.update(item_params)
      log_event(params[:id], 'status_update', "Status Updated to #{status}", session[:user_id])
      flash[:notice] = 'Item status updated successfully.'
      redirect_to @item
    else
      flash[:notice] = 'Error updating status. Status must be nil, Damaged, Lost, Not Available, or Intact.'
      render :show
    end
  end

  def get_valid_status(status)
    status = nil if status.blank?
    status
  end

  def item_params
    params.require(:item).permit(:item_id, :serial_number, :item_name,
                                 :category, :quality_score, :currently_available, :image, :details, :status, :comment)
  end

  def export
    respond_to do |format|
      format.html
      format.csv { send_data Item.to_csv, filename: "items-#{DateTime.now.strftime('%d%m%Y%H%M')}.csv" }
    end
  end

  def import # rubocop:disable Metrics/AbcSize,Metrics/MethodLength
    return redirect_to request.referer, notice: 'No file added' if params[:file].nil?
    return redirect_to request.referer, notice: 'Only CSV files allowed' unless params[:file].content_type == 'text/csv'

    opened_file = File.open(params[:file])
    options = { headers: true, col_sep: ',' }
    csv = CSV.parse(opened_file, **options)
    csv.each do |row|
      item_hash = { serial_number: '' }
      item_hash[:serial_number] = row['serial_number']
      item_hash[:item_name] = row['item_name']
      item_hash[:category] = row['category']
      item_hash[:currently_available] = true
      item_hash[:details] = row['details']
      item_hash[:quality_score] = 100

      puts '==================='
      puts row.to_hash
      puts '==================='

      Item.find_or_create_by!(item_hash)
      # for performance, you could create a separate job to import each user
      # CsvImportJob.perform_later(user_hash)
    end

    index
    render :index
  end
end

app/helpers/item_helper.rb
# frozen_string_literal: true

# Unused module
module ItemHelper
end

app/helpers/items_helper.rb
# frozen_string_literal: true

# Items utility methods
module ItemsHelper
  def icon_for_category(category) # rubocop:disable Metrics/MethodLength
    case category
    when 'Mobile Devices'
      'fa-mobile-alt'
    when 'Development Boards and Kits'
      'fa-regular fa-layer-group'
    when 'Sensors and Modules'
      'fa-solid fa-fingerprint'
    when 'Computer Accessories'
      'fa-solid fa-ethernet'
    when 'Displays'
      'fa-solid fa-desktop'
    when 'Furnitures'
      'fa-chair'
    else
      'fa-regular fa-layer-group'
    end
  end
end

app/views/items/export.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Create New Item - Stock'Em</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  <style>
      body {
          font-family: Arial, sans-serif;
          margin: 0;
          padding: 0;
          display: flex;
          flex-direction: column;
          min-height: 100vh;
          background-color: #f8f8f8;
      }
      header, footer {
          display: flex;
          justify-content: space-between;
          align-items: center;
          background-color: #500000;
          color: white;
          padding: 15px 20px;
      }
      .header-title {
          font-size: 30px;
          font-weight: bold;
      }
      .greeting {
          font-size: 20px;
          margin-right: 10px;
      }
      .form-container {
          margin: 20px auto;
          padding: 20px;
          background-color: #fff;
          border-radius: 10px;
          box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
          max-width: 600px;
          display: flex;
          flex-direction: column;
          box-sizing: border-box;
      }
      label {
          font-size: 16px;
          margin-top: 10px;
      }
      .required:after {
          content: " *";
          color: red;
      }
      input[type="text"], input[type="number"], textarea, select {
          padding: 10px;
          border: 2px solid #ccc;
          border-radius: 5px;
          width: 100%;
          margin-top: 5px;
          transition: border-color 0.3s;
          box-sizing: border-box;
          margin-bottom: 5%;
      }
      input[type="text"]:focus, input[type="number"]:focus, textarea:focus, select:focus {
          border-color: #500000;
          outline: none;
          margin-bottom: 5%;
      }
      .button-container {
          display: flex;
          justify-content: center;
          margin-top: 20px;
      }
      .submit-button {
          background-color: #500000;
          color: white;
          border: none;
          border-radius: 5px;
          padding: 10px 15px;
          font-size: 16px;
          cursor: pointer;
          transition: background-color 0.3s;
      }
      .submit-button:hover {
          background-color: #700000;
      }
      .user-icon {
          font-size: 20px;
          color: white;
      }

      /* Style for disabled option */
      select option:disabled {
          color: #aaa; /* Gray color for disabled options */
      }

      /* Prevent resizing of the textarea */
      textarea {
          resize: none; /* Disable resizing */
      }
  </style>
</head>
<body>
<div>
  <div class="form-container">
    <% if @evtype == "Export" %>
      <h2>Export Items</h2>
      <p>Copy the content below into a TSV file that can then be imported into other spreadsheets.</p>
    <% else %>
      <h2>Import Items</h2>
      <p>Copy-Paste a TSV file of item data into the box below.</p>
    <% end %>

    <%= form_tag(import_items_path, method: "get") do |form| %>

      <% if @evtype == "Export" %>
        <%= text_area_tag(:to_import, @output_content) %>
      <% else %>
        <%= text_area_tag(:to_import) %>
      <% end %>

      <% if @evtype == "Import" %>
      <div class="button-container">
          <input type="submit" value="Add Items" class="submit-button">
      </div>
      <% end %>

      <div class="button-container">
        <%= link_to 'Back', items_path, class: 'btn' %>
      </div>

    <% end %>

  </div>
</div>
</body>
</html>

app/views/items/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Stock'Em</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  <style>
      input[type="file"] {
          display: none;
      }
    .greeting {
      font-size: 20px; 
      margin-right: 10px; 
    }
    .search-container {
      margin: 20px;
      display: flex;
      align-items: center;
    }
    .search-form {
      display: flex;
      align-items: center;
      width: 100%; /* Make sure the form takes up the full width */
    }
    .search-container input[type="text"] {
      padding: 10px;
      border: 2px solid #ccc;
      border-radius: 5px;
      margin-right: 10px;
      flex: 1; 
      transition: border-color 0.3s; 
    }
    .search-container input[type="text"]:focus {
      border-color: #500000; 
      outline: none;
    }
    .search-bar {
      width: 150px; /* Reduce width of the search bar */
      padding: 5px;
    }
    .filter-dropdown {
      padding: 5px;
      width: 150px; /* Set a uniform width for dropdowns */
    }
    .filter label {
      margin-right: 20px; /* Add space between label and dropdowns/checkbox */
    }
    .btn.btn-primary {
      padding: 5px 10px;
    }
    .filter {
      display: flex;
      align-items: center;
      margin-left: 5px;
      font-size: 16px; 
      margin-right: 15px; 
    }
    .filter input {
      margin-right: 5px; 
      transform: scale(1.2); 
    }
    .card-container {
      display: flex;
      flex-direction: column;
      gap: 20px;
      margin: 20px 300px;
      height: 60vh; /* Fixed height for scrolling */
      overflow-y: auto; /* Enables scrolling */
      padding: 20px; /* Padding for the content */
      background-color: #fff; /* Background color for visibility */
      border-radius: 10px; /* Rounded corners */
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2); /* Shadow effect */
      text-decoration: none;
    }
    .card {
      background-color: #f5f5f5;
      border-radius: 10px;
      padding: 30px;
      display: flex; 
      align-items: center; 
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2); 
      transition: transform 0.2s, background-color 0.3s;
      text-decoration: none; 
    }
    .card:hover {
      transform: translateY(-5px); 
      background-color: #e0e0e0; 
    }
    .icon {
      font-size: 40px; 
      margin-right: 10px; 
      color: #500000; 
    }
    .user-icon {
      font-size: 20px; 
      color: white; 
    }
    .card-content {
      display: flex;
      flex-direction: column; 
    }
    .item-status {
      font-size: 14px; 
      margin-top: 5px;
    }
    h3 {
      margin: 10px 0 5px 0; 
      font-size: 18px; 
      color: #500000; 
    }
    p {
      margin: 0; 
      color: #666; 
    }
    .availability {
      font-weight: bold; 
      margin-top: 5px; 
    }
    .available {
      color: green; 
    }
    .not-available {
      color: red; 
    }
    .new-item-button {
      background-color: #500000;
      color: white;
      border: none;
      border-radius: 5px;
      padding: 10px 15px;
      font-size: 16px;
      cursor: pointer;
      transition: background-color 0.3s;
      margin: 20px auto; /* Centering with auto margins */
      display: inline-block; /* Makes it block-level for auto margin */
      text-decoration: none;
    }
    .new-item-button:hover {
      background-color: #700000;
    }
    .button-container {
      text-align: center; /* Center text inside the button container */
      margin: 20px 0; /* Add some vertical spacing */
    }
    .no-items-message {
      font-size: 18px;
      color: #777;
      text-align: center;
      margin-top: 20px;
    }
    .div-main{
      width: 100%;
      overflow: hidden;
    }
  </style>
  <script>
    function submitForm() {
      document.getElementById('filterForm').submit();
    }
  </script>
</head>
<body>
<div class="div-main">

  <div class="search-container">
    <%= form_with url: items_path, method: :get, local: true, id: 'filterForm', class: 'search-form' do %>

      <!-- Search by general query -->
      <%= text_field_tag :query, params[:query], placeholder: "Search...", class: "search-bar" %>

      <!-- Category Filter -->
      <label class="filter">
        <select name="category" id="category" class="filter-dropdown category" onchange="submitForm()">
          <option value="">All Categories</option>
          <% if @categories.present? %>
            <% @categories.each do |category| %>
              <option value="<%= category %>" <%= 'selected' if params[:category] == category %>><%= category %></option>
            <% end %>
          <% end %>
        </select>
      </label>

      <!-- Status Filter -->
      <label class="filter">
        <select name="status" id="status" class="filter-dropdown status" onchange="submitForm()">
          <option value="">All Statuses</option>
          <% if @statuses.present? %>
            <% @statuses.each do |status| %>
              <% if status.present? %>
                <option value="<%= status %>" <%= 'selected' if params[:status] == status %>><%= status.capitalize %></option>
              <% else %>
                <option value="unknown" <%= 'selected' if params[:status] == 'unknown' %>>Unknown</option>
              <% end %>
            <% end %>
          <% end %>
        </select>
      </label>

      <!-- Availability Filter -->
      <label class="filter">
        <%= check_box_tag :available_only, '1', params[:available_only] == '1', onchange: "submitForm()" %> Only show available items
      </label>

    <% end %>
  </div>

  <!-- Scrollable Card Container -->
  <div class="card-container">
    <% if @items.any? %>
      <% @items.each do |item| %>
        <%= link_to item_path(item), class: 'card' do %>
          <div class="icon">
            <i class="fas <%= icon_for_category(item.category) %>"></i>
          </div>
          <div class="card-content">
            <h3 class="item-name"><%= item.item_name %></h3>
            <p class="item-category"><%= item.category %></p>
            <span class="availability <%= item.currently_available ? 'available' : 'not-available' %>">
              <%= item.currently_available ? 'Available' : 'Not Available' %>
            </span>
            <p class="item-status">
              <strong>Status:</strong> <%= item.status.present? ? item.status : 'Unknown' %>
            </p>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <p class="no-items-message">No Result Found</p>
    <% end %>
  </div>

<% if @current_user.auth_level != 0 %>

    <%= form_tag({:controller => "items", :action => 'import'}, {:multipart => true}) do %>
      <div class="button-container">
        <%= link_to 'Create New Item', new_item_path, class: 'new-item-button' %>
        <%= link_to 'Export Items', export_items_path(format: 'csv', evtype: "Export"), class: 'new-item-button' %>
        <label for="file" class="new-item-button">Import Items</label>
        <%= file_field_tag('Import Items', {:name => "file", :onchange => 'this.form.submit()', :id => "file",
                                            :accept => ".csv"})  %>
        <input type="submit" value="PublishImportItemsASD">
      </div>

    <% end %>

<% end %>

</div>

<script>
  function submitForm() {
    document.getElementById("filterForm").submit();
document.addEventListener('DOMContentLoaded', function() {
    const flashMessage = document.querySelector('.flash-message');
    if (flashMessage) {
      setTimeout(function() {
        flashMessage.style.opacity = '0';
      }, 2000);
  
      setTimeout(function() {
        flashMessage.remove();
      }, 3000);
    }
  });
</script>

app/views/items/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Create New Item - Stock'Em</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
      display: flex;
      flex-direction: column;
      min-height: 100vh;
      background-color: #f8f8f8;
    }
    header, footer {
      display: flex;
      justify-content: space-between;
      align-items: center;
      background-color: #500000;
      color: white;
      padding: 12px 20px;
    }
    .header-title {
      font-size: 30px; 
      font-weight: bold; 
    }
    .greeting {
      font-size: 20px; 
      margin-right: 10px; 
    }
    .form-container {
      margin: 15px auto;
      padding: 15px;
      background-color: #fff;
      border-radius: 10px;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
      max-width: 600px;
      display: flex;
      flex-direction: column;
      box-sizing: border-box;
    }
    label {
      font-size: 16px;
      margin-top: 8px;
    }
    .required:after {
      content: " *";
      color: red;
    }
    input[type="text"], input[type="number"], textarea, select {
      padding: 8px;
      border: 2px solid #ccc;
      border-radius: 5px;
      width: 100%;
      margin-top: 4px;
      transition: border-color 0.3s;
      box-sizing: border-box;
      margin-bottom: 3%;
    }
    input[type="text"]:focus, input[type="number"]:focus, textarea:focus, select:focus {
      border-color: #500000;
      outline: none;
      margin-bottom: 3%;
    }
    .button-container {
      display: flex;
      justify-content: center;
      margin-top: 15px;
      margin-bottom: 10px;
    }
    .submit-button {
      background-color: #500000;
      color: white;
      border: none;
      border-radius: 5px;
      padding: 10px 15px;
      font-size: 16px;
      cursor: pointer;
      transition: background-color 0.3s;
    }
    .submit-button:hover {
      background-color: #700000;
    }
    .user-icon {
      font-size: 20px; 
      color: white; 
    }
    select option:disabled {
      color: #aaa;
    }
    textarea {
      resize: none;
    }
    h2 {
      margin-top: 0;
      margin-bottom: 15px;
      text-align: center; /* Center the heading */
      color: #500000; /* Added to match theme */
      font-size: 24px; /* Slightly larger */
    }
  </style>
</head>
<body>
<div>
<div class="form-container">
  <h2>Create New Item</h2>

  <%= form_with(model: @item, local: true) do |form| %>
    <!-- Authenticity token for CSRF protection is automatically handled by form_with -->
  <% if @item.errors.any? %>
    <div class="error-messages">
      <h3><%= pluralize(@item.errors.count, "error") %> prevented this item from being saved:</h3>
      <ul>
        <% @item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    
   <label for="item_name" class="required">Item Name</label>
<%= form.text_field :item_name, id: 'item_name', required: true, minlength: 3, maxlength: 50 %>

<% categories = JSON.parse(File.read(Rails.root.join('app/assets/data/category.json')))['data'] %>
<label for="category" class="required">Category</label>
<%= form.select :category, options_for_select(categories.map { |category| [category, category] }, @item.category), { prompt: 'Select a category' }, { id: 'category', required: true } %>

<label for="quality_score" class="required">Quality Score</label>
<%= form.number_field :quality_score, 
    id: 'quality_score', 
    min: 0, 
    max: 100, 
    required: true,
    oninput: "this.value = Math.min(Math.max(this.value, 0), 100)" 
%>

<label for="currently_available" class="required">Currently Available</label>
<%= form.select :currently_available, options_for_select([['Select availability', ''], ['Yes', true], ['No', false]], @item.currently_available), id: 'currently_available', required: true %>

<label for="serial_number" class="required">Serial Number</label>
<%= form.text_field :serial_number, id: 'serial_number', required: true %>

<label for="details">Details</label>
<%= form.text_field :details, id: 'details', required: false %>

<div class="button-container">
  <%= form.submit 'Create Item', class: 'submit-button' %>
</div>

  <% end %>
</div>
</div>
</body>
</html>